//! The fixed module head renders byte-exact to the schema-rust golden prelude: the
//! `// @generated` marker, the four scalar aliases packed as one block, and the
//! cfg-gated NOTA import — the block every generated wire module opens with,
//! identical for every schema.

use core_nomos::{GENERATED_MARKER, ModuleHead};

/// The exact head bytes every schema-rust golden opens with: the marker comment, a
/// blank line, the four scalar aliases packed with no blank between them, a blank
/// line, the cfg-gated NOTA import, and a trailing blank line before the first
/// declaration.
const GOLDEN_HEAD: &str = "// @generated by schema-rust\n\n#[rustfmt::skip]\npub type String = std::string::String;\n#[rustfmt::skip]\npub type Integer = u64;\n#[rustfmt::skip]\npub type Boolean = bool;\n#[rustfmt::skip]\npub type Path = std::string::String;\n\n#[rustfmt::skip]\n#[cfg(feature = \"nota-text\")]\npub use nota::{NotaDecodeError, NotaEncode, NotaSource};\n\n";

#[test]
fn the_fixed_module_head_renders_byte_exact() {
    let rendered = ModuleHead::fixed()
        .render()
        .expect("render the module head");
    assert_eq!(rendered, GOLDEN_HEAD);
}

#[test]
fn render_sections_is_the_head_without_the_marker() {
    let head = ModuleHead::fixed();
    let sections = head.render_sections().expect("render sections");
    let expected = GOLDEN_HEAD
        .strip_prefix(GENERATED_MARKER)
        .and_then(|rest| rest.strip_prefix("\n\n"))
        .expect("the head opens with the marker and a blank line");
    assert_eq!(sections, expected);
}

#[test]
fn the_head_carries_two_blocks_the_scalar_aliases_and_the_import() {
    let head = ModuleHead::fixed();
    assert_eq!(
        head.blocks().len(),
        2,
        "scalar-alias block, then the import"
    );
    assert_eq!(head.blocks()[0].len(), 4, "four scalar aliases");
    assert_eq!(head.blocks()[1].len(), 1, "one NOTA import");
}
