//! The fixed generated-module head.
//!
//! Every generated wire module opens with the same, schema-independent head: the
//! `// @generated` marker comment, the four scalar type aliases
//! (`String`/`Integer`/`Boolean`/`Path`), and the cfg-gated NOTA import. It is a
//! fixed property of the module shape, not of any schema.
//!
//! It is held here as stringless logos-encoded-form data with its sibling NameTable and
//! rendered through the one TextualRust projection, so `prettyplease` stays the sole
//! formatter of the item bodies. The marker comment sits outside every item, so it
//! is prepended raw — the one raw-text seam, recorded as a lean.

use core_logos::{
    Alias, Attribute, ConfigurationPredicate, CoreItem, Generics, PathNode, TypeReference, Use,
    Visibility,
};
use name_table::{Identifier, Name, NameTable};
use textual_rust::RustSource;

use crate::error::NomosError;

/// The `// @generated by schema-rust` marker that heads every generated module. It
/// sits outside every item, so it is emitted raw — never through `prettyplease`.
pub const GENERATED_MARKER: &str = "// @generated by schema-rust";

/// The fixed module head as stringless CoreLogos data: an ordered list of prelude
/// blocks with their sibling NameTable. A block is the unit that renders as one
/// `prettyplease` pass — one output paragraph. The two blocks are the scalar-alias
/// group (four aliases that pack with no blank line between them) and the NOTA
/// import; the renderer separates the two blocks by a blank line.
pub struct ModuleHead {
    blocks: Vec<Vec<CoreItem>>,
    names: NameTable,
}

impl ModuleHead {
    /// The fixed head every generated wire module carries.
    pub fn fixed() -> Self {
        let mut author = PreludeAuthor::new();
        let scalar_aliases = author.scalar_aliases();
        let nota_import = author.nota_import();
        Self {
            blocks: vec![scalar_aliases, vec![nota_import]],
            names: author.into_names(),
        }
    }

    /// The projected prelude sections that sit between the marker and the module's
    /// declarations: each block rendered as a single `prettyplease` pass, the blocks
    /// separated by a blank line. Ends with a blank line, so the first declaration
    /// opens its own paragraph.
    pub fn render_sections(&self) -> Result<String, NomosError> {
        let mut text = String::new();
        for block in &self.blocks {
            let rendered = RustSource::project_items(block, &self.names)?;
            text.push_str(rendered.as_str());
            // The blank line that separates this block's paragraph from the next.
            text.push('\n');
        }
        Ok(text)
    }

    /// The full module head: the marker (raw), a blank line, then the projected
    /// prelude sections — the one-stop head the projection engine prepends ahead of a
    /// module's declaration items.
    pub fn render(&self) -> Result<String, NomosError> {
        let mut text = String::from(GENERATED_MARKER);
        text.push_str("\n\n");
        text.push_str(&self.render_sections()?);
        Ok(text)
    }

    /// The prelude blocks, in emission order — read access for tests and callers that
    /// want the stringless items rather than their rendered text.
    pub fn blocks(&self) -> &[Vec<CoreItem>] {
        &self.blocks
    }

    /// The sibling NameTable that resolves every identifier the blocks carry.
    pub fn names(&self) -> &NameTable {
        &self.names
    }
}

/// A private authoring cursor over a fresh NameTable: the data-bearing holder for the
/// interning verbs that build the fixed prelude items, so no free function carries
/// the interning state.
struct PreludeAuthor {
    names: NameTable,
}

impl PreludeAuthor {
    fn new() -> Self {
        Self {
            names: NameTable::new(),
        }
    }

    fn into_names(self) -> NameTable {
        self.names
    }

    fn identifier(&mut self, text: &str) -> Identifier {
        self.names.intern(Name::new(text))
    }

    fn path(&mut self, segments: &[&str]) -> PathNode {
        PathNode {
            segments: segments
                .iter()
                .map(|segment| self.identifier(segment))
                .collect(),
        }
    }

    fn rustfmt_skip(&mut self) -> Attribute {
        Attribute::ToolPath(self.path(&["rustfmt", "skip"]))
    }

    /// The four scalar aliases in their fixed order (`String`, `Integer`,
    /// `Boolean`, `Path`) — one block that packs with no blank line between aliases.
    fn scalar_aliases(&mut self) -> Vec<CoreItem> {
        [
            ("String", &["std", "string", "String"][..]),
            ("Integer", &["u64"]),
            ("Boolean", &["bool"]),
            ("Path", &["std", "string", "String"]),
        ]
        .into_iter()
        .map(|(name, target)| self.scalar_alias(name, target))
        .collect()
    }

    /// `#[rustfmt::skip] pub type <name> = <target>;`.
    fn scalar_alias(&mut self, name: &str, target: &[&str]) -> CoreItem {
        let attribute = self.rustfmt_skip();
        let name = self.identifier(name);
        let target = TypeReference::Path(self.path(target));
        CoreItem::Alias(Alias {
            visibility: Visibility::Public,
            attributes: vec![attribute],
            name,
            generics: Generics::none(),
            target,
        })
    }

    /// `#[rustfmt::skip] #[cfg(feature = "nota-text")] pub use nota::{…};`.
    fn nota_import(&mut self) -> CoreItem {
        let rustfmt_skip = self.rustfmt_skip();
        let feature = self.identifier("nota-text");
        let base = self.path(&["nota"]);
        let group = ["NotaDecodeError", "NotaEncode", "NotaSource"]
            .into_iter()
            .map(|name| self.identifier(name))
            .collect();
        CoreItem::Use(Use {
            visibility: Visibility::Public,
            attributes: vec![
                rustfmt_skip,
                Attribute::Cfg(ConfigurationPredicate::Feature(feature)),
            ],
            base,
            group,
        })
    }
}
