//! The fixed generated-module head.
//!
//! Every generated wire module opens with the schema-independent generated marker
//! and cfg-gated NOTA import. Scalar references lower directly to canonical Rust
//! types; generated modules contain no transparent type aliases.

use core_logos::{
    Attribute, ConfigurationPredicate, EncodedItem, NOTA, NOTA_DECODE_ERROR, NOTA_ENCODE,
    NOTA_SOURCE, NOTA_TEXT_FEATURE, PathNode, RUSTFMT, SKIP, Use, Visibility, standard_name_table,
};
use name_table::{IdentifierNamespace, NameTable, NameTableError};
use textual_rust::RustSource;

use crate::error::NomosError;

/// The `// @generated by schema-rust` marker that heads every generated module. It
/// sits outside every item, so it is emitted raw — never through `prettyplease`.
pub const GENERATED_MARKER: &str = "// @generated by schema-rust";

/// The fixed module head as stringless EncodedLogos data. The standard Logos slice
/// resolves the import's fixed identifiers; no local names are allocated here.
pub struct ModuleHead {
    blocks: Vec<Vec<EncodedItem>>,
    names: NameTable,
    creation_error: Option<NameTableError>,
}

impl ModuleHead {
    /// The fixed head every generated wire module carries.
    pub fn fixed() -> Self {
        let (names, creation_error) = match standard_name_table() {
            Ok(names) => (names, None),
            Err(error) => (
                NameTable::new(IdentifierNamespace::LogosStandard),
                Some(error),
            ),
        };
        let nota_import = EncodedItem::Use(Use {
            visibility: Visibility::Public,
            attributes: vec![
                Attribute::ToolPath(PathNode {
                    segments: vec![RUSTFMT, SKIP],
                }),
                Attribute::Cfg(ConfigurationPredicate::Feature(NOTA_TEXT_FEATURE)),
            ],
            base: PathNode {
                segments: vec![NOTA],
            },
            group: vec![NOTA_DECODE_ERROR, NOTA_ENCODE, NOTA_SOURCE],
        });
        Self {
            blocks: vec![vec![nota_import]],
            names,
            creation_error,
        }
    }

    /// The projected prelude sections that sit between the marker and the module's
    /// declarations. Each block renders as a single `prettyplease` pass and the
    /// returned text ends with a blank line before the first declaration.
    pub fn render_sections(&self) -> Result<String, NomosError> {
        if let Some(error) = &self.creation_error {
            return Err(error.clone().into());
        }
        let mut text = String::new();
        for block in &self.blocks {
            let rendered = RustSource::project_items(block, &self.names)?;
            text.push_str(rendered.as_str());
            text.push('\n');
        }
        Ok(text)
    }

    /// The full module head: marker, blank line, then projected prelude sections.
    pub fn render(&self) -> Result<String, NomosError> {
        let mut text = String::from(GENERATED_MARKER);
        text.push_str("\n\n");
        text.push_str(&self.render_sections()?);
        Ok(text)
    }

    /// The prelude blocks in emission order.
    pub fn blocks(&self) -> &[Vec<EncodedItem>] {
        &self.blocks
    }

    /// The standard NameTable slice that resolves every prelude identifier.
    pub fn names(&self) -> &NameTable {
        &self.names
    }
}
